# Generated by Django 3.1 on 2021-01-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210108_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
